import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Images } from "lucide-react";

const MEDIA_SLOTS = [
  { label: "Hero (wide)", key: "heroWide" },
  { label: "Macro / Texture", key: "macroTexture" },
  { label: "Ingredients Flatlay", key: "ingredientsFlatlay" },
  { label: "Whole Dish", key: "wholeDish" },
] as const;

export default function MediaPage() {
  return (
    <div className="max-w-4xl">
      <div className="mb-8">
        <h1 className="text-2xl font-serif font-bold text-stone-900">
          Media
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Recipe images are generated by AI and stored on the CDN.
        </p>
      </div>

      <div className="grid grid-cols-2 gap-5">
        {MEDIA_SLOTS.map((slot) => (
          <Card key={slot.key}>
            <div className="aspect-[4/3] bg-muted/50 border-b border-border flex items-center justify-center">
              <Images size={32} className="text-muted-foreground/30" />
            </div>
            <CardHeader>
              <CardTitle className="text-sm">{slot.label}</CardTitle>
              <CardDescription>
                Auto-generated per recipe. Uploads coming soon.
              </CardDescription>
            </CardHeader>
          </Card>
        ))}
      </div>
    </div>
  );
}